apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  schemaVersion: "1.0"  # Replace with the appropriate schema version
  inbound:
    - name: AWS Marketplace Integration
      port: 8080
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
